# Generated by Django 2.2.5 on 2019-10-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='Phon_number',
        ),
    ]
